version: "3"

services:
  black-key-proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - WORKSPACE=app
    restart: always
    env_file:
      - .env.docker
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
    networks:
      - backend

networks:
  backend:
    external: true
